import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// __dirname is not available in ES modules — we derive it from import.meta.url
const __dirname = fileURLToPath(new URL('.', import.meta.url));

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      // 'aws-blocks' resolves to the client file generated by the backend server.
      // This is what makes  import { api } from 'aws-blocks'  work in the browser.
      'aws-blocks': resolve(__dirname, 'aws-blocks/client.js'),
    },
  },
  server: {
    port: 3100,
    proxy: {
      // Forward the config.json discovery request to the backend
      '/.blocks-sandbox': 'http://localhost:3001',
      // Forward all JSON-RPC API calls to the backend
      '/aws-blocks/api': 'http://localhost:3001',
    },
  },
});
